# Sa-Token 配置
sa-token:
  # Token名称
  token-name: satoken
  # Token有效期
  timeout: 2592000
  # Token风格
  token-style: uuid

  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s

